#          Copyright Jamie Allsop 2026-2026
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

#-------------------------------------------------------------------------------
#   C++ Profiles enforce header generation and compile-time -include helpers
#-------------------------------------------------------------------------------

import os
import re

from cuppa.toolchains.cxx_modules_support import effective_build_dir


_ENFORCE_ATTR_RE = re.compile(
    r'\[\s*\[\s*profiles\s*::\s*enforce\s*\(',
    re.MULTILINE,
)


def profiles_build_dir( env ):
    path = os.path.join( effective_build_dir( env ), 'profiles' )
    if not os.path.isdir( path ):
        try:
            os.makedirs( path )
        except OSError:
            if not os.path.isdir( path ):
                raise
    return path


def format_enforce_attribute( names ):
    """Return a TU-first empty-declaration for the given profile designators."""
    designators = [ name.strip() for name in names if name and name.strip() ]
    if not designators:
        return ''
    return '[[profiles::enforce({})]];'.format( ', '.join( designators ) )


def enforce_header_path( env, names ):
    designators = [ name.strip() for name in names if name and name.strip() ]
    if not designators:
        return None
    # Stable filename from the designator list so rebuilds share one header.
    safe = '_'.join(
        re.sub( r'[^A-Za-z0-9]+', '_', name ).strip( '_' ) or 'profile'
        for name in designators
    )
    return os.path.join( profiles_build_dir( env ), 'enforce_{}.hpp'.format( safe ) )


def ensure_enforce_header( env, names ):
    """Write the enforce empty-declaration header; return its absolute path."""
    path = enforce_header_path( env, names )
    if not path:
        return None
    attribute = format_enforce_attribute( names )
    content = (
        '/* Generated by cuppa --profiles-enforce; do not edit. */\n'
        '{}\n'
        .format( attribute )
    )
    previous = None
    if os.path.isfile( path ):
        with open( path, 'r' ) as handle:
            previous = handle.read()
    if previous != content:
        with open( path, 'w' ) as handle:
            handle.write( content )
    try:
        env.Clean( env.Dir( env['build_dir'] ), path )
    except Exception:
        pass
    return path


def source_has_profiles_enforce( source_path ):
    """True when the translation unit already opens with profiles::enforce."""
    if not source_path or not os.path.isfile( source_path ):
        return False
    try:
        with open( source_path, 'r', errors='replace' ) as handle:
            # Attribute must be the first declaration; checking the preamble is enough.
            text = handle.read( 4096 )
    except OSError:
        return False
    return bool( _ENFORCE_ATTR_RE.search( text ) )


def profiles_enforce_include_flags( env, source_path=None ):
    """Return ``['-include', path]`` when enforce injection is active for this TU."""
    header = env.get( '_cuppa_profiles_enforce_header' )
    if not header:
        return []
    if source_path and source_has_profiles_enforce( str( source_path ) ):
        return []
    return [ '-include', header ]


def append_profiles_enforce_include( env, cxx_flags, source_path=None ):
    """Append enforce ``-include`` flags to a CXXFLAGS list when needed."""
    flags = list( cxx_flags )
    extra = profiles_enforce_include_flags( env, source_path=source_path )
    if not extra:
        return flags
    # Avoid duplicating an identical -include already present.
    for index in range( len( flags ) - 1 ):
        if flags[index] == '-include' and flags[index + 1] == extra[1]:
            return flags
    flags.extend( extra )
    return flags
