#          Copyright Jamie Allsop 2026-2026
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

#-------------------------------------------------------------------------------
#   Conan Package Manager — export-pkg publisher for Cuppa-built artefacts
#-------------------------------------------------------------------------------

"""Publish Cuppa-built libraries as Conan 2 packages (prebuilt export-pkg).

Cuppa remains the build orchestrator: compile/link with SCons first, then
``conan export-pkg`` packages staged headers/libs and optionally
``conan upload`` to a remote when ``--publish-package`` is set.

See ``design/archive/conan-publish-plan.md``.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess

from cuppa.build_with_conan import (
    _find_conan_executable,
    conan_settings_for,
    settings_to_cli,
)
from cuppa.colourise import as_error, as_info, as_notice
from cuppa.log import logger
from cuppa.utility.scons_nodes import resolve_existing_node_path as _resolve_node_path


_CONANFILE_TEMPLATE = '''\
# Generated by Cuppa ConanPackagePublisher — package prebuilt artefacts only.
from conan import ConanFile
from conan.tools.files import copy
import os


class CuppaPrebuiltConan(ConanFile):
    name = "{name}"
    version = "{version}"
    package_type = "{package_type}"
    settings = "os", "compiler", "build_type", "arch"
    options = {{"shared": [True, False]}}
    default_options = {{"shared": {shared_default}}}
{requires_attr}
    def package(self):
        include_src = os.path.join(self.recipe_folder, "include")
        lib_src = os.path.join(self.recipe_folder, "lib")
        modules_src = os.path.join(self.recipe_folder, "modules")
        if os.path.isdir(include_src):
            copy(self, "*", src=include_src,
                 dst=os.path.join(self.package_folder, "include"))
        if os.path.isdir(lib_src):
            copy(self, "*", src=lib_src,
                 dst=os.path.join(self.package_folder, "lib"))
        if os.path.isdir(modules_src):
            copy(self, "*", src=modules_src,
                 dst=os.path.join(self.package_folder, "modules"))
{requirements_method}
    def package_info(self):
        self.cpp_info.libs = {libs!r}
        if os.path.isdir(os.path.join(self.package_folder, "modules")):
            self.cpp_info.set_property("cuppa_modules_dir", "modules")
'''


def detect_library_names( lib_dir ):
    """Infer cpp_info.libs names from staged static/shared library files."""
    if not lib_dir or not os.path.isdir( lib_dir ):
        return []
    names = []
    seen = set()
    for entry in sorted( os.listdir( lib_dir ) ):
        path = os.path.join( lib_dir, entry )
        if not os.path.isfile( path ):
            continue
        lib = None
        if entry.startswith( 'lib' ) and entry.endswith( '.a' ):
            lib = entry[3:-2]
        elif entry.startswith( 'lib' ) and '.so' in entry:
            lib = entry[3:].split( '.so' )[0]
        elif entry.startswith( 'lib' ) and entry.endswith( '.dylib' ):
            lib = entry[3:-6]
        elif entry.endswith( '.lib' ):
            lib = entry[:-4]
        if lib and lib not in seen:
            seen.add( lib )
            names.append( lib )
    return names


def package_type_for_libs( lib_dir ):
    if not lib_dir or not os.path.isdir( lib_dir ):
        return 'static-library'
    for entry in os.listdir( lib_dir ):
        if '.so' in entry or entry.endswith( '.dylib' ) or entry.endswith( '.dll' ):
            return 'shared-library'
    return 'static-library'


def package_type_for_shared( shared ):
    """Map publisher shared= flag to Conan package_type."""
    if shared is True:
        return 'shared-library'
    if shared is False:
        return 'static-library'
    return None


def conan_reference( name, version, user=None, channel=None ):
    ref = '{}/{}'.format( name, version )
    if user:
        ref = '{}@{}'.format( ref, user )
        if channel:
            ref = '{}/{}'.format( ref, channel )
    elif channel:
        # Conan requires user when channel is set
        ref = '{}@_/{}'.format( ref, channel )
    return ref


def write_prebuilt_conanfile(
        path,
        name,
        version,
        libs,
        package_type='static-library',
        shared=False,
        requires=None,
):
    parent = os.path.dirname( path )
    if parent:
        os.makedirs( parent, exist_ok=True )

    requires_list = list( requires ) if requires else []
    if requires_list:
        requires_attr = '    requires = {!r}\n'.format( tuple( requires_list ) )
        requirements_method = ''
    else:
        requires_attr = ''
        requirements_method = ''

    contents = _CONANFILE_TEMPLATE.format(
            name=name,
            version=version,
            package_type=package_type,
            shared_default=bool( shared ),
            requires_attr=requires_attr,
            requirements_method=requirements_method,
            libs=list( libs ),
    )
    with open( path, 'w', encoding='utf-8' ) as handle:
        handle.write( contents )
    return path


def write_conan_profile( path, settings ):
    """Write a Conan 2 profile containing the given settings (host=build)."""
    parent = os.path.dirname( path )
    if parent:
        os.makedirs( parent, exist_ok=True )
    lines = [ '[settings]' ]
    for key in sorted( settings ):
        value = settings[key]
        if value is None:
            continue
        lines.append( '{}={}'.format( key, value ) )
    lines.append( '' )
    with open( path, 'w', encoding='utf-8' ) as handle:
        handle.write( '\n'.join( lines ) )
    return path


class ConanPackagePublisher:
    """Duck-typed publisher for ``env.PublishPackage`` (see GitlabPackagePublisher)."""

    def __init__(
            self,
            env,
            name=None,
            version=None,
            user=None,
            channel=None,
            remote=None,
            remote_url=None,
            source_include_dir=None,
            source_lib_dir=None,
            libs=None,
            conanfile=None,
            shared=None,
            requires=None,
            source_modules_dir=None,
    ):
        from SCons.Script import Flatten

        if not name or not version:
            import SCons.Errors
            raise SCons.Errors.StopError(
                "ConanPackagePublisher requires name= and version="
            )

        self._env = env
        self._name = str( name )
        self._version = str( version )
        self._user = user
        self._channel = channel
        self._remote = remote
        self._remote_url = remote_url
        self._libs_override = list( libs ) if libs else None
        self._shared = shared
        self._requires = list( requires ) if requires else []
        self._conanfile_override = None

        self._source_include_dir = env.Dir( str( source_include_dir ) ) if source_include_dir else None
        self._source_lib_dir = env.Dir( str( source_lib_dir ) ) if source_lib_dir else None
        self._source_modules_dir = (
            env.Dir( str( source_modules_dir ) ) if source_modules_dir else None
        )

        if conanfile:
            self._conanfile_override = env.File( str( conanfile ) )

        stage_name = 'conan_pkg_{}_{}'.format( self._name, self._version )
        self._stage_dir = env.Dir( os.path.join( env['final_dir'], stage_name ) )
        self._stage_include = env.Dir( os.path.join( str( self._stage_dir ), 'include' ) )
        self._stage_lib = env.Dir( os.path.join( str( self._stage_dir ), 'lib' ) )
        self._stage_modules = env.Dir( os.path.join( str( self._stage_dir ), 'modules' ) )
        self._conanfile_path = os.path.join( str( self._stage_dir ), 'conanfile.py' )

        stamp = '{name}-{version}.conan.pkg'.format( name=self._name, version=self._version )
        published = '{name}-{version}.conan.published'.format(
                name=self._name, version=self._version
        )
        self._package_location = env.File( os.path.join( env['abs_final_dir'], stamp ) )
        self._package_published_id = env.File( os.path.join( env['abs_final_dir'], published ) )

        self._reference = conan_reference(
                self._name, self._version, user=self._user, channel=self._channel
        )

        self._clean_targets = Flatten( [ self._stage_dir ] )

    def build_package( self, target, source, env ):
        conan = _find_conan_executable()
        if not conan:
            logger.error( "Conan CLI not found on PATH; cannot export-pkg [{}]".format(
                    as_error( self._reference )
            ) )
            return 1

        stage = str( self._stage_dir )
        if os.path.isdir( stage ):
            shutil.rmtree( stage )
        os.makedirs( stage, exist_ok=True )

        if self._source_include_dir:
            src_inc = _resolve_node_path( self._source_include_dir )
            if os.path.isdir( src_inc ):
                shutil.copytree( src_inc, str( self._stage_include ) )
            else:
                logger.warn( "Conan package [{}]: include dir [{}] missing".format(
                        as_notice( self._name ), as_notice( src_inc )
                ) )
                os.makedirs( str( self._stage_include ), exist_ok=True )
        else:
            os.makedirs( str( self._stage_include ), exist_ok=True )

        if self._source_lib_dir:
            src_lib = _resolve_node_path( self._source_lib_dir )
            if os.path.isdir( src_lib ):
                # Exclude our own stage/stamp artefacts so copytree cannot nest
                # when source_lib_dir is abs_final_dir (stage lives under final/).
                shutil.copytree(
                        src_lib,
                        str( self._stage_lib ),
                        ignore=self._lib_copy_ignore,
                )
            else:
                logger.warn( "Conan package [{}]: lib dir [{}] missing".format(
                        as_notice( self._name ), as_notice( src_lib )
                ) )
                os.makedirs( str( self._stage_lib ), exist_ok=True )
        else:
            os.makedirs( str( self._stage_lib ), exist_ok=True )

        self._stage_modules_tree()

        if self._conanfile_override:
            src_recipe = _resolve_node_path( self._conanfile_override )
            if not os.path.isfile( src_recipe ):
                logger.error(
                    "ConanPackagePublisher conanfile= [{}] not found".format(
                            as_error( src_recipe )
                    )
                )
                return 1
            shutil.copy2( src_recipe, self._conanfile_path )
            if self._requires:
                logger.warn(
                    "Conan package [{}]: requires= ignored when conanfile= is set "
                    "(declare requires in the hand-written recipe)".format(
                            as_notice( self._name )
                    )
                )
        else:
            libs = self._libs_override
            if libs is None:
                libs = detect_library_names( str( self._stage_lib ) )
            if not libs:
                logger.warn( "Conan package [{}]: no libraries detected under [{}]".format(
                        as_notice( self._name ), as_notice( str( self._stage_lib ) )
                ) )

            pkg_type = package_type_for_shared( self._shared )
            if pkg_type is None:
                pkg_type = package_type_for_libs( str( self._stage_lib ) )
            shared_default = (
                self._shared if self._shared is not None
                else ( pkg_type == 'shared-library' )
            )
            write_prebuilt_conanfile(
                    self._conanfile_path,
                    self._name,
                    self._version,
                    libs,
                    package_type=pkg_type,
                    shared=shared_default,
                    requires=self._requires,
            )

        toolchain = env.get( 'toolchain' )
        variant = env.get( 'variant' )
        settings = conan_settings_for( env, toolchain, variant )
        profile_path = write_conan_profile(
                os.path.join( stage, 'cuppa_profile' ),
                settings,
        )
        cmd = [
            conan, 'export-pkg', stage,
            '--name', self._name,
            '--version', self._version,
            '-tf', '',
            '-pr:a', profile_path,
        ]
        if self._user:
            cmd.extend( [ '--user', str( self._user ) ] )
        if self._channel:
            cmd.extend( [ '--channel', str( self._channel ) ] )
        if self._shared is not None:
            cmd.extend( [ '-o', 'shared={}'.format( bool( self._shared ) ) ] )
        # Keep explicit -s as belt-and-braces with the generated profile.
        cmd.extend( settings_to_cli( settings ) )

        logger.info( "Running [{}]".format( as_notice( ' '.join( cmd ) ) ) )
        completed = subprocess.run(
                cmd,
                check=False,
                capture_output=True,
                text=True,
        )
        if completed.returncode != 0:
            detail = ( completed.stderr or completed.stdout or '' ).strip()
            logger.error( "conan export-pkg for [{}] failed:\n{}".format(
                    as_error( self._reference ), as_error( detail )
            ) )
            return completed.returncode

        stamp = str( target[0] )
        parent = os.path.dirname( stamp )
        if parent:
            os.makedirs( parent, exist_ok=True )
        with open( stamp, 'w', encoding='utf-8' ) as handle:
            handle.write( self._reference + '\n' )
            handle.write( 'settings=' + ','.join(
                    '{}={}'.format( k, settings[k] ) for k in sorted( settings )
            ) + '\n' )
        logger.info( "Conan package [{}] exported to local cache".format(
                as_info( self._reference )
        ) )
        return None

    def publish_package( self, target, source, env ):
        from SCons.Script import Touch

        if env.get( 'offline' ):
            logger.error(
                "Cannot upload Conan package [{}] while --offline; "
                "export-pkg may still have updated the local cache.".format(
                        as_error( self._reference )
                )
            )
            return 1

        if not self._remote:
            logger.error(
                "ConanPackagePublisher for [{}] requires remote= to upload "
                "(pass remote='name' and optionally remote_url=...).".format(
                        as_error( self._reference )
                )
            )
            return 1

        conan = _find_conan_executable()
        if not conan:
            logger.error( "Conan CLI not found on PATH; cannot upload [{}]".format(
                    as_error( self._reference )
            ) )
            return 1

        ensure_rc = self._ensure_remote( conan )
        if ensure_rc:
            return ensure_rc

        cmd = [
            conan, 'upload', self._reference,
            '-r', str( self._remote ),
            '-c',
        ]
        logger.info( "Running [{}]".format( as_notice( ' '.join( cmd ) ) ) )
        completed = subprocess.run(
                cmd,
                check=False,
                capture_output=True,
                text=True,
        )
        if completed.returncode != 0:
            detail = ( completed.stderr or completed.stdout or '' ).strip()
            logger.error( "conan upload for [{}] failed:\n{}".format(
                    as_error( self._reference ), as_error( detail )
            ) )
            return completed.returncode

        env.Execute( Touch( target[0] ) )
        logger.info( "Conan package [{}] uploaded to remote [{}]".format(
                as_info( self._reference ), as_info( str( self._remote ) )
        ) )
        return None

    def _modules_source_path( self ):
        """Resolve BMI modules dir: explicit source_modules_dir or lib_dir/modules."""
        if self._source_modules_dir:
            return _resolve_node_path( self._source_modules_dir )
        if self._source_lib_dir:
            candidate = os.path.join( _resolve_node_path( self._source_lib_dir ), 'modules' )
            map_path = os.path.join( candidate, 'module-map.json' )
            if os.path.isfile( map_path ):
                return candidate
        return None

    def _stage_modules_tree( self ):
        src_modules = self._modules_source_path()
        if not src_modules:
            return
        if not os.path.isdir( src_modules ):
            logger.warn( "Conan package [{}]: modules dir [{}] missing".format(
                    as_notice( self._name ), as_notice( src_modules )
            ) )
            return
        map_path = os.path.join( src_modules, 'module-map.json' )
        if not os.path.isfile( map_path ):
            logger.warn(
                "Conan package [{}]: modules dir [{}] has no module-map.json; skipping".format(
                        as_notice( self._name ), as_notice( src_modules )
                )
            )
            return
        shutil.copytree( src_modules, str( self._stage_modules ) )
        logger.info( "Conan package [{}]: staged modules from [{}]".format(
                as_info( self._name ), as_notice( src_modules )
        ) )

    def _ensure_remote( self, conan ):
        listed = subprocess.run(
                [ conan, 'remote', 'list' ],
                check=False,
                capture_output=True,
                text=True,
        )
        remote_names = []
        if listed.returncode == 0 and listed.stdout:
            for line in listed.stdout.splitlines():
                # "name: url [Verify SSL: ...]"
                match = re.match( r'^([^:]+):', line.strip() )
                if match:
                    remote_names.append( match.group( 1 ).strip() )

        if self._remote in remote_names:
            return None

        if not self._remote_url:
            logger.error(
                "Conan remote [{}] is not configured and remote_url= was not provided".format(
                        as_error( str( self._remote ) )
                )
            )
            return 1

        cmd = [ conan, 'remote', 'add', str( self._remote ), str( self._remote_url ) ]
        logger.info( "Running [{}]".format( as_notice( ' '.join( cmd ) ) ) )
        completed = subprocess.run( cmd, check=False, capture_output=True, text=True )
        if completed.returncode != 0:
            detail = ( completed.stderr or completed.stdout or '' ).strip()
            logger.error( "Failed to add Conan remote [{}]: {}".format(
                    as_error( str( self._remote ) ), as_error( detail )
            ) )
            return completed.returncode
        return None

    def _lib_copy_ignore( self, directory, names ):
        ignored = set()
        stage_basename = os.path.basename( str( self._stage_dir ) )
        for name in names:
            if name == 'modules' or name == stage_basename:
                ignored.add( name )
            elif name.startswith( 'conan_pkg_' ):
                ignored.add( name )
            elif name.endswith( '.conan.pkg' ) or name.endswith( '.conan.published' ):
                ignored.add( name )
        return ignored

    def sources( self ):
        # Include headers as SCons sources when they live outside the package
        # stamp directory. Do **not** add ``source_lib_dir`` when it is
        # ``abs_final_dir`` (the usual case): the stamp file lives under that
        # Dir, and listing the Dir as a Command source creates a dependency
        # cycle. Library rebuilds are already covered by the ``source``
        # argument to ``env.PublishPackage(lib, publisher)``.
        sources = []
        if self._source_include_dir:
            inc = os.path.realpath( str( self._source_include_dir ) )
            stamp_parent = os.path.realpath( os.path.dirname( str( self._package_location ) ) )
            if inc != stamp_parent and not inc.startswith( stamp_parent + os.sep ):
                sources.append( self._source_include_dir )
        if self._conanfile_override:
            sources.append( self._conanfile_override )
        return sources

    def package_published( self ):
        return self._package_published_id

    def package( self ):
        return self._package_location

    def clean_targets( self ):
        return self._clean_targets

    def reference( self ):
        return self._reference
